# Generated by Django 4.1.1 on 2022-09-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='resgister_id',
        ),
    ]
