# Generated by Django 4.1.1 on 2022-09-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_ingredients_recipe_labels_recipe_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='labels',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_steps',
            field=models.CharField(max_length=100),
        ),
    ]
