# Generated by Django 4.1.1 on 2022-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
