# Generated by Django 4.1.1 on 2022-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_recipe_ingredient_remove_recipe_recipe_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reccipe_step',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Reccipe_step',
        ),
    ]
