# Generated by Django 4.1.1 on 2022-09-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_reccipe_step_recipe_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
